### PR TITLE
wp_ulike_get_comment_likes: Allows getting the number of likes on a c…

### PR DESCRIPTION
**Pull request by waclawjacek**
…omment

### CODE REVIEW

**Comment by waclawjacek** [comment]
@Alimir Hey, could you please provide some feedback on why this wasn't merged? Did you not like the feature or did the code get outdated?

**Comment by Alimir** [comment]
Hi @waclawjacek 
Sorry for my late answer. This is because we've already added this functionality by mentioning your name in the plugin. :)

**Comment by waclawjacek** [comment]
@Alimir Cool, thanks for the heads-up!

**Comment by Alimir** [comment]
@waclawjacek You're welcome. I hope to see you again with new developments. (This time, I will be sure to track by Git) :)

**Pull request closed without merging**
